
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "8.0.0"

[[constraint]]
  name = "github.com/coreos/go-oidc"

[[constraint]]
  name = "github.com/emicklei/go-restful-swagger12"
  version = "1.0.1"

[[constraint]]
  name = "github.com/ghodss/yaml"

[[constraint]]
  name = "github.com/gogo/protobuf"

[[constraint]]
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/golang/groupcache"

[[constraint]]
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/google/gofuzz"

[[constraint]]
  name = "github.com/googleapis/gnostic"

[[constraint]]
  name = "github.com/gophercloud/gophercloud"

[[constraint]]
  name = "github.com/gregjones/httpcache"

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"

[[constraint]]
  name = "github.com/imdario/mergo"

[[constraint]]
  branch = "master"
  name = "github.com/juju/ratelimit"

[[constraint]]
  name = "github.com/peterbourgon/diskv"
  version = "2.0.1"

[[constraint]]
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/apimachinery"
