# vendor in code gen tools
required = ["github.com/golang/mock/mockgen", "github.com/jteeuwen/go-bindata/go-bindata", "k8s.io/kubernetes/cmd/libs/go2idl/defaulter-gen"]

[[constraint]]
  branch = "master"
  name = "github.com/fsouza/go-dockerclient"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  name = "github.com/mholt/archiver"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "k8s.io/client-go"

[[constraint]]
  revision = "25d3523359ff17dda6deb867a7c3dd6c8b7ea705"
  name = "k8s.io/kubernetes"

[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  revision = "a0ff2567cfb70903282db057e799fd826784d41d"

# TODO: Update once changes are released
[[constraint]]
  name = "github.com/jetstack-experimental/vault-unsealer"
  revision = "cea1258b2833b938e168e86dffaa980bd89f74c3"

# TODO: Update once changes are released
[[constraint]]
  name = "github.com/jetstack-experimental/vault-helper"
  revision = "f7506c9c9ab6cb68dfbb3be12161cae30336875c"
